stages:
  - fetest
  - betest


default:
  image: docker:24.0.5-cli
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info


# ##########Reusable code for all containers##########

# ##Node setup##
# .setup_node: &setup_node
#   - apk update
#   - apk add nodejs npm
#   - npm -v
#   - node -v
#   - cd frontend && ls -al | grep package.json

# ##Install Dependencies##
# .install_deps: &install_deps
#   - npm ci --cache ../.npm && ls -al | grep node_modules

# ##Cache setup##
# .cache_pull: &cache_pull
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - .npm/
#     policy: pull


# frontend_build:
#   stage: fetest
#   tags:
#     - DinD
#   script:
#     - *setup_node
#     - ls -al | grep node_modules >> /dev/null || echo "node_modules not found"
#     - *install_deps
  
#   cache:
#     key: ${CI_COMMIT_REF_SLUG}
#     paths:
#       - .npm/
#     policy: pull-push


# test_unit:
#   stage: fetest
#   needs: [frontend_build]
#   tags:
#     - DinD
#   cache: *cache_pull
#   script:
#     - *setup_node
#     - *install_deps
#     - npm run test:ci


# ##Container3
# linting_test:
#   stage: fetest
#   needs: [frontend_build]
#   tags:
#     - DinD
#   cache: *cache_pull
#   script:
#     - *setup_node
#     - *install_deps
#     - npm run lint && echo "✅ Linting passed with no errors!"





######Reusable code for backend tests######

.cache_pull_backend: &cache_pull_backend
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .mvn/
    policy: pull

.build_backend: &build_backend
  - apk update
  - apk add maven openjdk17
  - pwd
  - ls -al
  - cd backend && ls -al | grep pom.xml

backend_build:
  stage: betest
  tags:
    - DinD
  script:
    - *build_backend
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - .mvn/
    policy: pull-push

backend_unit_test:
  stage: betest
  needs:
    - backend_build
  tags:
    - DinD
  cache: *cache_pull_backend
  script:
    - *build_backend  
    - cd backend && ./mvnw test

backend_linting_test:
  stage: betest
  needs:
    - backend_build
  tags:
    - DinD
  cache: *cache_pull_backend
  script:
    - *build_backend
    - cd backend && ./mvnw checkstyle:check && echo "✅ Checkstyle passed with no errors!"