stages:
  - test
  - build
  - deploy

test:
  stage: test
  image: eclipse-temurin:21-jdk
  services:
    - name: postgres:15
      alias: postgres
      command: ["postgres", "-c", "listen_addresses='*'"]
      environment:
        POSTGRES_DB: my_database
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 12345678
      ports:
        - 5432:5432
      health_check:
        test: ["CMD-SHELL", "pg_isready -U postgres -d my_database -h localhost"]
        interval: 10s
        timeout: 5s
        retries: 5
  script:
    - echo "Running backend tests..."
    - cd backend
    - ./mvnw test

