stages:
  - build


default:
  image: docker:24.0.5-cli
  services:
    - docker:24.0.5-dind
  before_script:
    - docker info


build:
  stage: build
  tags:
    - DinD
  script:
    - hostname
    - pwd
    - whoami
    - cat /etc/os-release
    - apk add openjdk-21-jdk
    - java -version

