env:
  BRANCH_NAME: ${{ github.ref_name }}
  DOCKER_REPO: nhkyaw/visit-record-app

on:
  workflow_call:

jobs: 
  deploy:
    runs-on: ubuntu-latest
    if: github.ref_name == 'dev' || github.ref_name == 'uat' || github.ref_name == 'main' || github.ref_name == 'master'

    steps:
      - name: Map branch to environment #$GITHUB_ENV is a special file that sets environment variables for future steps in a job.
        run: |
          if [[ "${GITHUB_REF_NAME}" == "main" ]]; then
            echo "ENV=prod" >> $GITHUB_ENV
          else
            echo "ENV=${GITHUB_REF_NAME}" >> $GITHUB_ENV
          fi

      - name: checkout code
        uses: actions/checkout@v4   

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false


# terraform destroy -auto-approve -var="environment=${{ inputs.environment }}"
      - name: Terraform apply
        working-directory: terraform
        run: |
          terraform init -backend-config="key=env/${ENV}/terraform.tfstate"
          terraform apply -auto-approve -var-file="${ENV}.tfvars"
          terraform destroy -auto-approve -var-file="${ENV}.tfvars" #Temporary until TF code is stable

      - name: Get EC2 public IP
        working-directory: terraform
        run: |
          EC2_IP=$(terraform output -raw ec2_public_ip)
                
          if [ -z "$EC2_IP" ] || [ "$EC2_IP" == "null" ]; then
            echo "ERROR: EC2_IP is empty. Check if 'output' is defined in .tf files."
              exit 1
          fi
                
          echo "EC2_IP=$EC2_IP" >> $GITHUB_ENV

      - name: Verify EC2 IP
        run: |
          echo "EC2_IP from Env: [${{ env.EC2_IP }}]"

      - name: Prepare SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2.pem
          chmod 600 ~/.ssh/ec2.pem

      - name: Wait for EC2 SSH to be ready
        run: |
          echo "Waiting for SSH on $EC2_IP..."
          for i in {1..30}; do
            if ssh -o StrictHostKeyChecking=no \
                  -o ConnectTimeout=5 \
                  -i ~/.ssh/ec2.pem \
                  ubuntu@${EC2_IP} "echo SSH ready"; then
              echo "SSH is ready!"
              exit 0
            fi
            echo "Still booting... retry in 10s"
            sleep 10
          done

          echo "ERROR: EC2 did not become ready in time"
          exit 1
      - name: Add EC2 to known_hosts
        run: |
          ssh-keyscan -H ${{ env.EC2_IP }} >> ~/.ssh/known_hosts

      - name: Copy docker directory to EC2 (scp)
        run: |
          scp -i ~/.ssh/ec2.pem -r docker ubuntu@$EC2_IP:~/

      - name: Set Docker tag
        run: |
          if [[ "${BRANCH_NAME}" == "main" || "${BRANCH_NAME}" == "master" ]]; then
            echo "IMAGE_TAG=prod" >> $GITHUB_ENV
          else
            echo "IMAGE_TAG=${BRANCH_NAME}" >> $GITHUB_ENV
          fi

      # - name: Deploy on EC2
      #   run: |
      #     echo "Waiting for SSH connection on $EC2_IP..."

      #     for i in $(seq 1 30); do
      #       if ssh -T \
      #         -o StrictHostKeyChecking=no \
      #         -o ConnectTimeout=5 \
      #         -o BatchMode=yes \
      #         -i ~/.ssh/ec2.pem \
      #         ubuntu@$EC2_IP "echo SSH ready"; then

      #         echo "SSH is ready!"

      #         ssh -T \
      #           -o StrictHostKeyChecking=no \
      #           -o BatchMode=yes \
      #           -i ~/.ssh/ec2.pem \
      #           ubuntu@$EC2_IP << 'EOF'
      #         set -e

      #         export PATH="/usr/bin:/usr/local/bin:/snap/bin:$PATH"

      #         cd ~/docker

      #         docker --version
      #         docker compose version

      #         echo "Deploying IMAGE_TAG=$IMAGE_TAG"

      #         docker pull nhkyaw/visit-record-app:backend-$IMAGE_TAG
      #         docker pull nhkyaw/visit-record-app:frontend-$IMAGE_TAG

      #         docker compose down
      #         docker compose --env-file .env.$IMAGE_TAG -f docker-compose.yaml up -d
      #         EOF

      #         exit 0
      #       fi

      #       echo "Attempt $i: SSH not ready yet, retrying in 10s..."
      #       sleep 10
      #     done

      #     echo "ERROR: EC2 did not become ready in time"
      #     exit 1





      # - name: Set File Permission for deploy.sh
      #   run: | 
      #     chmod +x deploy.sh

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ env.EC2_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          envs: IMAGE_TAG,DOCKER_REPO 
          # script_path: deploy.sh
          script: |
            set -e
            uptime >> /home/ubuntu/docker/data.log
            whoami >> /home/ubuntu/docker/data.log      
            pwd >> /home/ubuntu/docker/data.log
            groups >> /home/ubuntu/docker/data.log
            printenv | grep -i IMAGE_TAG && echo "IMAGE_TAG is set" >> /home/ubuntu/docker/data.log || echo "IMAGE_TAG not set" >> /home/ubuntu/docker/data.log
            pwd >> /home/ubuntu/docker/data.log
            /usr/bin/docker --version >> /home/ubuntu/docker/data.log
            /usr/bin/docker compose version >> /home/ubuntu/docker/data.log

            sudo chmod +x /home/ubuntu/docker/deploy.sh
            /home/ubuntu/docker/deploy.sh


            # sudo docker pull ${DOCKER_REPO}:backend-${IMAGE_TAG}
            # sudo docker pull ${DOCKER_REPO}:frontend-${IMAGE_TAG}
            
            # sudo docker compose down
            # sudo docker compose --env-file .env.${IMAGE_TAG} -f docker-compose.yaml up -d


