name: Full Pipeline

on:
  push:
    branches: [main]

jobs:

  # 1. TEST PHASE 
  test-app:
    uses: ./.github/workflows/test.yaml

  # 1. BUILD PHASE
  build-java:
    needs: [test-app]
    uses: ./.github/workflows/build.yaml
    with:
      stack: 'java'

  build-react:
    needs: [test-app]
    uses: ./.github/workflows/build.yaml
    with:
      stack: 'react'



  # 3. DEPLOY PHASE (Runs only if Tests succeed)
  deploy-app:
    needs: [test-app]
    uses: ./.github/workflows/deploy.yaml
    secrets: inherit # Pass secrets like AWS_ACCESS_KEY to the child